<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>JavaWebApi</groupId>
    <artifactId>JavaWebApi</artifactId>
    <version>0.0.1-SNAPSHOT</version>
  </parent>
  <artifactId>app-repository</artifactId>
  <name>app-repository</name>
  <description>repositoprio de acceso a datos comun a todos los proyectos</description>
  
  <dependencies>
		<dependency>
			<groupId>JavaWebApi</groupId>
			<artifactId>app-domain</artifactId>
			<version>0.0.1-SNAPSHOT</version>
		</dependency>
	</dependencies>
  
</project>